### ISSUE TITLE
Spolier alert

### ISSUE THREAD

**Issue by ralts00** [yersoncp/js-fronteros-miniretos-t1#2]
Gracias por los retos voy a comenzar hoy, pero me da miedo ver tus resultados o soluciones en la primera página, podrías ocultarlos ? O dejarlos en algún lugar que no sea el readme ? O en alguna especie de lugar donde no se vean ? Pd cómo crees que debéis hacerlo ? Un fork e ir subiendo ?? Soy nuevo programando

**Comment by yersoncp** [comment]
Hola @ralts00 
Gracias por tu sugerencia, se agradece. Las soluciones han sido ocultados para mostrar dándole click.
Un abrazo.
Update: En estos casos lo normal es que hagas un fork de este repo y hagas cambios, si crees que debo incluir tus cambios en mi rama me mandas un pull request.

**Comment by ralts00** [comment]
Gracias :D
